### ISSUE TITLE
Errors since you add more than one story ('_createElementVNode' has already been declared)

### ISSUE THREAD

**Issue by JNietou** [nuxt-modules/storybook#456]
If I add one more component to the equation, the storybook breaks. With the following error:
![image](https://github.com/nuxt-modules/storybook/assets/148975938/41ef2853-00c9-446c-9d64-497aa5ef4898)

![image](https://github.com/nuxt-modules/storybook/assets/148975938/7d0b71f7-6543-4f66-bdd2-f10f2c129f86)

Reproduction (don't forget to stop the console and `npm run storybook`):
[nuxt3 simplest example](https://stackblitz.com/edit/nuxt-starter-mamfhc)

I would also like to know how I can run my app independently in dev mode via `npm run dev` without the storybook also opening.
Right now if you run npm run dev, both open. And I don't always need to open storybook.

**Comment by filiphazardous** [comment]
@JNietou This bug may have been fixed by @storybook-vue/nuxt 0.2.0

If you want to start nuxt in dev mode without storybook, you may try to add a condition for when to add the storybook module to `modules` in `nuxt.config.[ts|js]` (you could look for an env variable that you define, as an example).

**Comment by tobiasdiez** [comment]
Is still an issue? Could you please update the reproduction in this case to use the newest versions. Thanks!

Having storybook dev server independent of nuxt dev server is https://github.com/nuxt-modules/storybook/issues/555.

**Comment by tobiasdiez** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.
