### ISSUE TITLE
'The entry point "vue" cannot be marked as external' after installing Nuxt Storybook module

### ISSUE THREAD

**Issue by MooseSaeed** [nuxt-modules/storybook#656]
## Description:

I encountered an issue after installing the Nuxt Storybook module in a new Nuxt project. Upon running `yarn dev`, the following error appears in the console:

```bash
✘ [ERROR] The entry point "vue" cannot be marked as external
```

## Steps to Reproduce:

1. Create a new Nuxt project using `npx nuxi@latest init my-project`
2. Navigate to the project directory: `cd my-project`
3. Install the Nuxt Storybook module: `npx nuxi@latest module add storybook`
4. Run the development server: `yarn dev`

## Expected Behavior:

The Nuxt development server should start without errors, and the Storybook module should be correctly initialized.

## Actual Behavior:

The storybook server fails to start, and the following error is shown in the console:

```bash
✘ [ERROR] The entry point "vue" cannot be marked as external
```

## Repro:

https://github.com/MooseSaeed/test-nuxt

## Additional Context:

I have not made any other changes to the default configuration of the new Nuxt project. This error appears to be directly related to the Nuxt Storybook module.

**Comment by blowsie** [comment]
Me too

**Comment by tobiasdiez** [comment]
Yes, this should be fixed in the main branch. It might take a couple of days until we release it. Alternatively, it should work if you downgrade nuxt to v 3.11.x

**Comment by MooseSaeed** [comment]
@tobiasdiez I tried to downgrade nuxt to v 3.11 and 3.10 but still getting the same issue

**Comment by blowsie** [comment]
Worked for me, be sure to remove a `^` symbol in the package json if you have one
