### ISSUE TITLE
Multiple story export make Context conflict

### ISSUE THREAD

**Issue by phs-playnomm** [nuxt-modules/storybook#773]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.1
- Nuxt Version:     3.13.1
- CLI Version:      3.13.1
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      ssr, devtools, app, build, sourcemap, modules, gtag, imports, typescript, runtimeConfig, alias, i18n, css, vite, compatibilityDate
- Runtime Modules:  @nuxtjs/storybook@8.2.0, @nuxt/content@2.13.2, @nuxtjs/i18n@8.5.2, @pinia/nuxt@0.4.11, nuxt-gtag@2.1.0, @nuxt/image@1.8.0
- Build Modules:    -

### Reproduction

https://github.com/nuxt-modules/storybook/tree/main/examples/showcase

### Describe the bug

![스크린샷 2024-09-09 오후 5 42 55](https://github.com/user-attachments/assets/cb859e73-0f25-4387-bf12-e0383da18d1a)

in NovaIcon.stories.ts

export const FillsReply: Story = {
  args: {
    icon: { type: 'fill', name: 'reply' },
    size: 24,
  },
}

export const FillsShare: Story = {
  args: {
    icon: { type: 'fill', name: 'share' },
    size: 24,
  },
}

**Comment by tobiasdiez** [comment]
This issue has been resolved in the latest nightly release. For installation instructions, please refer to: https://storybook.nuxtjs.org/getting-started/setup#nightly-builds. If you experience any further problems, don't hesitate to reopen this or create a new issue.

**Comment by ralfgoeke** [comment]
Hi, first off, thanks for your work, @tobiasdiez!

I can confirm that this error is still there. I'm getting the exact same error, as soon as I add a second story:

```ts
import type { Meta, StoryObj } from '@storybook-vue/nuxt';

import HelloWorld from '@/components/snippets/HelloWorld.vue';

const meta: Meta<typeof HelloWorld> = {
	tags: ['autodocs'],
	title: 'HelloWorld',
	component: HelloWorld,
};

export default meta;
type Story = StoryObj<typeof HelloWorld>;

export const Default: Story = {
	args: {
		text: 'Hello World',
	},
};

export const Another: Story = {
	args: {
		text: 'Hello World 2!',
	},
};
```

![CleanShot 2024-09-09 at 13 22 46](https://github.com/user-attachments/assets/ab39b889-1949-440f-ad4c-ebf67db4484b)

I'm using the nightly and tried it along with nuxt 3.13.0. 3.13.1 and the nuxt nightly as well.

**Comment by ralfgoeke** [comment]
Damn, I seem to have forgotten to throw away package-lock.json when I first tested with the nightlies.
It now works!
Sorry for that! :(

**Comment by tobiasdiez** [comment]
No problem! Happy to hear this is indeed fixed!
